# Generated by Django 5.2 on 2025-04-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('jan', models.FloatField(null=True)),
                ('feb', models.FloatField(null=True)),
                ('mar', models.FloatField(null=True)),
                ('apr', models.FloatField(null=True)),
                ('may', models.FloatField(null=True)),
                ('jun', models.FloatField(null=True)),
                ('jul', models.FloatField(null=True)),
                ('aug', models.FloatField(null=True)),
                ('sep', models.FloatField(null=True)),
                ('oct', models.FloatField(null=True)),
                ('nov', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('annual', models.FloatField(null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_data.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_data.region')),
            ],
        ),
    ]
